// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_slice: dynamic(() => import("./AboutUsSlice")),
  contact_slice: dynamic(() => import("./ContactSlice")),
  cta_slice: dynamic(() => import("./CtaSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
  testimonials_slice: dynamic(() => import("./TestimonialsSlice")),
  why_us_slice: dynamic(() => import("./WhyUsSlice")),
};
