// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_slice: dynamic(() => import("./HeroSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
};
