// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_slice: dynamic(() => import("./CtaSlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  services_slice: dynamic(() => import("./ServicesSlice")),
  why_us_slice: dynamic(() => import("./WhyUsSlice")),
};
